#!/usr/bin/env python3
"""
02_run_transformations.py
=========================
Transforms bronze landing tables into the gold unified marketing performance mart.

Execution paths (auto-detected):
  First run  (gold table absent):  3 quarantine MERGEs + CREATE OR REPLACE TABLE
                                   gold — all SQL generated by SqlBuilder.
  Incremental (gold table exists): 3 quarantine MERGEs (separate jobs) +
                                   3 gold MERGEs inside a single BEGIN/COMMIT
                                   transaction for atomicity.

Infrastructure bootstrap (runs before any BQ operation):
  _ensure_infrastructure() creates the three BigQuery datasets and the two
  metadata tables (audit + quarantine) with explicit schemas and DAY
  partitioning if they do not already exist.  Idempotent; safe to run every
  time.  Solves the "dataset not found" 404 on first deployment.

Quality guarantees (LLD §3):
  - OOP; single-responsibility classes; no global mutable state
  - Retry with exponential backoff (2s, 4s, 8s) on all BQ operations
  - AuditLogger: append-only ledger (no DML UPDATE; no string-escaping bugs)
  - Post-write verification: column count==30, row counts, spend reconciliation
  - maximum_bytes_billed on QueryJobConfig ONLY (never LoadJobConfig)
  - Logs to stdout + logs/02_run_transformations.log
  - sys.exit(1) on unrecoverable failure
"""

from __future__ import annotations

import argparse
import logging
import sys
import time
import uuid
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any

from google.api_core.exceptions import (
    BadRequest, DeadlineExceeded, InternalServerError,
    NotFound, ServiceUnavailable,
)
from google.cloud import bigquery

import common

# Inclusive [start, end] ISO-date bound applied to a batch's reads/writes.
# None means unbounded — today's full-history behaviour.
Window = tuple[str, str] | None


# =============================================================================
# Config
# =============================================================================

class Config:
    PROJECT           = common.PROJECT
    BRONZE_DS         = common.BRONZE_DS
    STAGING_DS        = common.STAGING_DS
    PRODUCTION_DS     = common.PRODUCTION_DS

    GOLD_TABLE        = "fct_unified_marketing_performance"
    AUDIT_TABLE       = "tbl_ingestion_audit"
    QUARANTINE_TABLE  = "stg_quarantine_logs"

    # Cost guardrails — QueryJobConfig ONLY (LLD §10.3)
    # FIRST_RUN_MAX_BYTES was the cap for CREATE OR REPLACE TABLE ... AS SELECT.
    # That operation is removed (see create_gold_schema + incremental_transaction).
    # Kept as a named constant for reference; not currently used in execution.
    FIRST_RUN_MAX_BYTES        = 5  * 1_024 ** 3   # 5 GB  — (legacy; unused)
    GOLD_MERGE_MAX_BYTES       = 1  * 1_024 ** 3   # 1 GB  — per-platform MERGE
    QUARANTINE_MERGE_MAX_BYTES = 50 * 1_024 ** 2   # 50 MB — tiny bronze scan
    VERIFY_MAX_BYTES           = 1  * 1_024 ** 3   # 1 GB  — INFORMATION_SCHEMA
    AUDIT_MAX_BYTES            = 10 * 1_024 ** 2   # 10 MB — audit load job
    # 3-platform transaction budget (3× single-MERGE cap)
    GOLD_TXN_MAX_BYTES         = 3  * 1_024 ** 3   # 3 GB  — BEGIN/COMMIT transaction

    MAX_RETRIES  = 3
    RETRY_BASE_S = 2   # waits: 2 s, 4 s, 8 s

    # BQ dataset location — must match the location of all source tables.
    # bronze tables are in US (confirmed by error messages); staging and
    # production are created with the same value in _ensure_infrastructure().
    BQ_LOCATION = "US"

    QUERIES_DIR = Path(__file__).resolve().parent / "queries"
    LOGS_DIR    = Path(__file__).resolve().parent / "logs"
    # FIRST_RUN_SQL removed — SqlBuilder.create_gold_schema() + incremental_transaction()
    # single source of truth; gold_unified_performance_mart.sql is doc-only.

    SPEND_TOLERANCE    = 0.01  # ± $0.01 for float reconciliation
    EXPECTED_GOLD_COLS = 30    # Data Contract; Script 07 also asserts this

    @classmethod
    def gold_ref(cls) -> str:
        return f"{cls.PROJECT}.{cls.PRODUCTION_DS}.{cls.GOLD_TABLE}"

    @classmethod
    def audit_ref(cls) -> str:
        return f"{cls.PROJECT}.{cls.STAGING_DS}.{cls.AUDIT_TABLE}"

    @classmethod
    def quarantine_ref(cls) -> str:
        return f"{cls.PROJECT}.{cls.STAGING_DS}.{cls.QUARANTINE_TABLE}"

    @classmethod
    def bronze_ref(cls, table: str) -> str:
        return f"{cls.PROJECT}.{cls.BRONZE_DS}.{table}"


# =============================================================================
# Logging
# =============================================================================

def setup_logging(log_file: Path) -> logging.Logger:
    return common.get_logger(log_file.stem)


# =============================================================================
# BQExecutor
# =============================================================================

_RETRYABLE = (InternalServerError, ServiceUnavailable, DeadlineExceeded)


class BQExecutor:
    """Executes BigQuery jobs with retry and cost guardrails. No business logic."""

    def __init__(self, client: bigquery.Client, log: logging.Logger) -> None:
        self._client = client
        self._log    = log

    def run_query(
        self, sql: str, max_bytes: int, description: str = "query",
    ) -> bigquery.QueryJob:
        cfg = bigquery.QueryJobConfig(
            maximum_bytes_billed=max_bytes, use_legacy_sql=False,
        )
        last_exc: Exception | None = None
        for attempt in range(1, Config.MAX_RETRIES + 1):
            try:
                job = self._client.query(sql, job_config=cfg)
                job.result()
                gb = (job.total_bytes_processed or 0) / 1_024 ** 3
                self._log.debug("[%s] OK  %.4f GB (attempt %d)", description, gb, attempt)
                return job
            except _RETRYABLE as exc:
                last_exc = exc
                if attempt < Config.MAX_RETRIES:
                    wait = Config.RETRY_BASE_S ** attempt
                    self._log.warning(
                        "[%s] Transient %s (attempt %d/%d) — retry in %ds",
                        description, type(exc).__name__, attempt, Config.MAX_RETRIES, wait,
                    )
                    time.sleep(wait)
                else:
                    self._log.error("[%s] Exhausted %d retries. Last: %s",
                                    description, Config.MAX_RETRIES, exc)
            except BadRequest as exc:
                self._log.error("[%s] BadRequest (non-retryable): %s", description, exc)
                raise
        raise RuntimeError(
            f"[{description}] Failed after {Config.MAX_RETRIES} attempts. Last: {last_exc}"
        ) from last_exc

    def load_rows(
        self,
        rows: list[dict[str, Any]],
        destination: str,
        job_config: bigquery.LoadJobConfig,
        description: str = "load",
    ) -> bigquery.LoadJob:
        """
        Batch-load via LoadJob — NO streaming buffer.
        Never use insert_rows_json: streaming buffer blocks UPDATE for ~90 min.
        LoadJobConfig does NOT accept maximum_bytes_billed (verified).
        """
        last_exc: Exception | None = None
        for attempt in range(1, Config.MAX_RETRIES + 1):
            try:
                job = self._client.load_table_from_json(rows, destination, job_config=job_config)
                job.result()
                self._log.debug("[%s] Load OK  %d row(s) (attempt %d)",
                                description, len(rows), attempt)
                return job
            except _RETRYABLE as exc:
                last_exc = exc
                if attempt < Config.MAX_RETRIES:
                    wait = Config.RETRY_BASE_S ** attempt
                    self._log.warning("[%s] Transient load error (attempt %d/%d) — retry in %ds",
                                      description, attempt, Config.MAX_RETRIES, wait)
                    time.sleep(wait)
            except Exception as exc:
                self._log.error("[%s] Load error: %s", description, exc)
                raise
        raise RuntimeError(
            f"[{description}] Load failed after {Config.MAX_RETRIES} attempts."
        ) from last_exc

    def table_exists(self, full_table_id: str) -> bool:
        try:
            self._client.get_table(full_table_id)
            return True
        except NotFound:
            return False



# =============================================================================
# AuditLogger  —  Append-Only Ledger Pattern
# =============================================================================
# Design decision (replaces UPDATE-based pattern):
#
#   WHY: tbl_ingestion_audit is unpartitioned. Every UPDATE DML scans the whole
#   table.  As the table grows past Config.AUDIT_MAX_BYTES (10 MB), the UPDATE
#   for the FAILED state exceeds the cost guardrail and throws BadRequest —
#   blinding the monitoring system at the exact moment you need it most.
#   Additionally, the previous _sql_literal helper's manual string escaping
#   ('replace single-quotes with backslash-single-quote') generates invalid BQ
#   SQL when error messages contain apostrophes, producing the "Unclosed string
#   literal" crash seen in production.
#
#   FIX: Every lifecycle event writes a NEW ROW via load_table_from_json.
#   No DML UPDATE ever runs.  No string escaping needed.  JSON handles all
#   special characters correctly.
#
#   Downstream reporting (latest status per run):
#     SELECT * EXCEPT (rn)
#     FROM (
#       SELECT *, ROW_NUMBER() OVER (
#           PARTITION BY audit_id ORDER BY last_updated_at DESC) AS rn
#       FROM `{STAGING_DS}.tbl_ingestion_audit`
#     ) WHERE rn = 1
# =============================================================================

class AuditLogger:
    """
    Append-only event log for one pipeline run.
    Each status change inserts a fresh row; no UPDATEs are issued.
    """

    def __init__(self, executor: BQExecutor, log: logging.Logger) -> None:
        self._ex         = executor
        self._log        = log
        self.audit_id    = str(uuid.uuid4())
        self._started_at: str = ""
        self._bronze_rows: int = 0

    # ── Public phase methods ─────────────────────────────────────────────────

    def started(self, bronze_row_count: int) -> None:
        self._started_at  = datetime.now(timezone.utc).isoformat()
        self._bronze_rows = bronze_row_count
        self._insert_event(status="STARTED")
        self._log.info("Audit row inserted  audit_id=%s  bronze_rows=%d",
                       self.audit_id, bronze_row_count)

    def transforming(self, mode: str) -> None:
        """mode: 'FIRST_RUN' or 'INCREMENTAL'"""
        self._insert_event(status=f"TRANSFORMING_{mode}")

    def verifying(self) -> None:
        self._insert_event(status="VERIFYING")

    def success(self, rows_accepted: int, rows_quarantined: int) -> None:
        self._insert_event(
            status="SUCCESS",
            rows_accepted=rows_accepted,
            rows_quarantined=rows_quarantined,
            rows_merged=rows_accepted,
            completed_at=datetime.now(timezone.utc).isoformat(),
        )

    def failed(self, error_message: str, error_stage: str) -> None:
        # No string escaping needed — load_table_from_json uses JSON serialization
        self._insert_event(
            status="FAILED",
            error_message=error_message[:4_096],
            error_stage=error_stage,
            completed_at=datetime.now(timezone.utc).isoformat(),
        )

    # ── Internal ─────────────────────────────────────────────────────────────

    def _insert_event(self, **override_fields: Any) -> None:
        """Insert one audit event row; all special characters safe via JSON."""
        row: dict[str, Any] = {
            "audit_id":         self.audit_id,
            "file_name":        "gold_transformation",
            "file_size_bytes":  None,
            "platform":         "all",
            "started_at":       self._started_at,
            "last_updated_at":  datetime.now(timezone.utc).isoformat(),
            "completed_at":     None,
            "rows_in_file":     self._bronze_rows,
            "rows_accepted":    None,
            "rows_quarantined": None,
            "rows_merged":      None,
            "status":           "UNKNOWN",
            "error_message":    None,
            "error_stage":      None,
        }
        row.update(override_fields)
        self._ex.load_rows(
            rows=[row],
            destination=Config.audit_ref(),
            job_config=bigquery.LoadJobConfig(
                source_format=bigquery.SourceFormat.NEWLINE_DELIMITED_JSON,
                write_disposition=bigquery.WriteDisposition.WRITE_APPEND,
            ),
            description=f"audit:{row['status']}",
        )


# =============================================================================
# SqlBuilder  —  Single Source of Truth for all SQL
# =============================================================================
# Design decisions (addresses all three brief issues):
#
# 1. DRY: _PLATFORM_CONFIG drives ALL SQL generation.  gold_unified_performance
#    _mart.sql is now regenerated from this class and is a documentation
#    artifact only — no separate copy to maintain.
#
# 2. engagement_rate removed from Level-1 bronze reads for ALL platforms.
#    Root cause of the production error: tiktok_ads_landing has no
#    engagement_rate column. Fix: compute it in Level-2 from social metrics
#    that ARE present in every bronze table (or default to 0 where absent):
#      SAFE_DIVIDE(likes + shares + comments, impressions)
#    G8 validation is removed — a SAFE_DIVIDE result is always ∈ [0, ∞), and
#    a computed metric does not need bronze-level quarantine gating.
#
# 3. Transaction isolation: incremental_transaction() wraps all 3 platform
#    gold MERGEs in BEGIN TRANSACTION / COMMIT TRANSACTION.  If TikTok's MERGE
#    fails after Facebook and Google commit, BigQuery rolls back the whole
#    transaction.  The quarantine MERGEs remain outside the transaction
#    (they are idempotent via MD5 key; no rollback needed).
# =============================================================================

class SqlBuilder:
    """
    Generates all BigQuery SQL from one _PLATFORM_CONFIG dict.
    Call quarantine_merge(platform), gold_merge(platform),
    create_gold_schema(), incremental_transaction() — each returns a
    complete, executable SQL string.
    """

    # ── Platform configuration (single source of truth) ──────────────────────
    # l1_metrics format: (gold_col, bronze_col_or_None, bq_type, hardcoded_default)
    #   bronze_col = None  →  use hardcoded_default
    #   bronze_col = str   →  CAST(COALESCE(NULLIF(bronze_col,''),'0') AS bq_type)
    # quarantine_extra_cols: columns needed for platform-specific G-checks
    #   (universal G1-G5 columns are always included; G8 removed globally)

    _PLATFORM_CONFIG: dict[str, dict] = {
        'Facebook': {
            'name_literal':  "'Facebook'",
            'origin':        'facebook_gold_validation',
            'bronze_table':  'facebook_ads_landing',
            'sub_id_col':    'ad_set_id',
            'sub_name_col':  'ad_set_name',
            'l1_metrics': [
                ('impressions',             'impressions',  'INT64',   None ),
                ('clicks',                  'clicks',       'INT64',   None ),
                ('spend',                   'spend',        'FLOAT64', None ),
                ('conversions',             'conversions',  'INT64',   None ),
                ('conversion_value',         None,          'FLOAT64', '0.0'),
                ('video_views',             'video_views',  'INT64',   None ),
                ('video_watch_25',           None,          'INT64',   '0'  ),
                ('video_watch_50',           None,          'INT64',   '0'  ),
                ('video_watch_75',           None,          'INT64',   '0'  ),
                ('video_watch_100',          None,          'INT64',   '0'  ),
                ('likes',                    None,          'INT64',   '0'  ),
                ('shares',                   None,          'INT64',   '0'  ),
                ('comments',                 None,          'INT64',   '0'  ),
                ('reach',                   'reach',        'INT64',   None ),
                ('frequency',               'frequency',    'FLOAT64', None ),
                ('quality_score',            None,          'INT64',   '0'  ),
                ('search_impression_share',  None,          'FLOAT64', '0.0'),
                ('avg_cpc',                  None,          'FLOAT64', '0.0'),
            ],
            'roas_expr': 'CAST(0.0 AS FLOAT64)',
            # G7 (frequency) and G10 (reach) — platform-specific quarantine checks
            # G8 (engagement_rate) intentionally absent — computed metric, not raw
            'quarantine_checks': [
                ('G7_INVALID_FREQUENCY',          'frequency > 0.0 AND frequency < 1.0'),
                ('G10_REACH_EXCEEDS_IMPRESSIONS', 'reach > impressions'),
            ],
            # Extra bronze columns needed for the quarantine checks above
            'quarantine_extra_cols': [
                ('frequency', 'frequency', 'FLOAT64'),
                ('reach',     'reach',     'INT64'  ),
            ],
            'gold_where_extra': '(frequency = 0.0 OR frequency >= 1.0) AND reach <= impressions',
        },

        'Google': {
            'name_literal':  "'Google'",
            'origin':        'google_gold_validation',
            'bronze_table':  'google_ads_landing',
            'sub_id_col':    'ad_group_id',
            'sub_name_col':  'ad_group_name',
            'l1_metrics': [
                ('impressions',             'impressions',             'INT64',   None ),
                ('clicks',                  'clicks',                  'INT64',   None ),
                ('spend',                   'cost',                    'FLOAT64', None ),  # cost → spend
                ('conversions',             'conversions',             'INT64',   None ),
                ('conversion_value',        'conversion_value',        'FLOAT64', None ),
                ('video_views',              None,                     'INT64',   '0'  ),
                ('video_watch_25',           None,                     'INT64',   '0'  ),
                ('video_watch_50',           None,                     'INT64',   '0'  ),
                ('video_watch_75',           None,                     'INT64',   '0'  ),
                ('video_watch_100',          None,                     'INT64',   '0'  ),
                ('likes',                    None,                     'INT64',   '0'  ),
                ('shares',                   None,                     'INT64',   '0'  ),
                ('comments',                 None,                     'INT64',   '0'  ),
                ('reach',                    None,                     'INT64',   '0'  ),
                ('frequency',                None,                     'FLOAT64', '0.0'),
                ('quality_score',           'quality_score',           'INT64',   None ),
                ('search_impression_share', 'search_impression_share', 'FLOAT64', None ),
                ('avg_cpc',                 'avg_cpc',                 'FLOAT64', None ),
            ],
            'roas_expr': 'SAFE_DIVIDE(conversion_value, spend)',
            'quarantine_checks': [
                ('G6_INVALID_QUALITY_SCORE',           'quality_score != 0 AND (quality_score < 1 OR quality_score > 10)'),
                ('G9_INVALID_SEARCH_IMPRESSION_SHARE', 'search_impression_share < 0.0 OR search_impression_share > 1.0'),
            ],
            'quarantine_extra_cols': [
                ('quality_score',           'quality_score',           'INT64'  ),
                ('search_impression_share', 'search_impression_share', 'FLOAT64'),
            ],
            'gold_where_extra': '(quality_score = 0 OR (quality_score >= 1 AND quality_score <= 10)) AND search_impression_share >= 0.0 AND search_impression_share <= 1.0',
        },

        'TikTok': {
            'name_literal':  "'TikTok'",
            'origin':        'tiktok_gold_validation',
            'bronze_table':  'tiktok_ads_landing',
            'sub_id_col':    'adgroup_id',
            'sub_name_col':  'adgroup_name',
            # NOTE: tiktok_ads_landing has NO engagement_rate column — it is
            # NEVER read here.  It is computed from likes/shares/comments in L2.
            'l1_metrics': [
                ('impressions',             'impressions',   'INT64',   None ),
                ('clicks',                  'clicks',        'INT64',   None ),
                ('spend',                   'cost',          'FLOAT64', None ),  # cost → spend
                ('conversions',             'conversions',   'INT64',   None ),
                ('conversion_value',         None,           'FLOAT64', '0.0'),
                ('video_views',             'video_views',   'INT64',   None ),
                ('video_watch_25',          'video_watch_25','INT64',   None ),
                ('video_watch_50',          'video_watch_50','INT64',   None ),
                ('video_watch_75',          'video_watch_75','INT64',   None ),
                ('video_watch_100',         'video_watch_100','INT64',  None ),
                ('likes',                   'likes',         'INT64',   None ),
                ('shares',                  'shares',        'INT64',   None ),
                ('comments',               'comments',       'INT64',   None ),
                ('reach',                   None,            'INT64',   '0'  ),
                ('frequency',               None,            'FLOAT64', '0.0'),
                ('quality_score',           None,            'INT64',   '0'  ),
                ('search_impression_share', None,            'FLOAT64', '0.0'),
                ('avg_cpc',                 None,            'FLOAT64', '0.0'),
            ],
            'roas_expr': 'CAST(0.0 AS FLOAT64)',
            'quarantine_checks': [
                ('G11_VIDEO_FUNNEL_MONOTONICITY', 'NOT(video_watch_25 >= video_watch_50 AND video_watch_50 >= video_watch_75 AND video_watch_75 >= video_watch_100)'),
                ('G12_VIDEO_WATCH_EXCEEDS_VIEWS', 'video_watch_25 > video_views'),
            ],
            'quarantine_extra_cols': [
                ('video_views',    'video_views',    'INT64'),
                ('video_watch_25', 'video_watch_25', 'INT64'),
                ('video_watch_50', 'video_watch_50', 'INT64'),
                ('video_watch_75', 'video_watch_75', 'INT64'),
                ('video_watch_100','video_watch_100','INT64'),
            ],
            'gold_where_extra': '(video_watch_25 >= video_watch_50 AND video_watch_50 >= video_watch_75 AND video_watch_75 >= video_watch_100) AND video_watch_25 <= video_views',
        },
    }

    # ── Private template helpers ──────────────────────────────────────────────

    @classmethod
    def _cast_expr(cls, bronze_col: str | None, bq_type: str, default: str | None) -> str:
        """
        Generate a safe cast expression for one bronze column.

        For columns read from bronze (all-STRING):
          COALESCE(SAFE_CAST(NULLIF(col, '') AS TYPE), 0)
          — NULLIF handles empty strings ('' → NULL)
          — SAFE_CAST handles un-castable values ('N/A', '1,050', 'null' → NULL)
            instead of crashing the pipeline on bad upstream exports
          — COALESCE provides the zero default (avoids NULLs in NOT NULL columns)

        For hardcoded defaults (bronze_col=None):
          CAST(literal AS TYPE) — no string parsing, always valid.
        """
        if bronze_col is not None:
            return f"COALESCE(SAFE_CAST(NULLIF({bronze_col}, '') AS {bq_type}), 0)"
        return f"CAST({default} AS {bq_type})"

    @staticmethod
    def _iso(d: str) -> str:
        return date.fromisoformat(d).isoformat()   # fail closed: only real ISO dates reach SQL

    @classmethod
    def _validated_bounds(cls, window: Window) -> tuple[str, str] | None:
        """
        One shared place for window validation: real ISO dates (via `_iso`) and
        `lo <= hi`. Both the bronze source filter and the gold target predicate
        call this, so a reversed range fails closed before either SQL string
        is built.
        """
        if window is None:
            return None
        lo, hi = (cls._iso(d) for d in window)
        if lo > hi:
            raise ValueError(f"window start {lo!r} is after end {hi!r}")
        return lo, hi

    @classmethod
    def _bronze_window(cls, window: Window) -> str:
        """Bronze `date` is an ISO STRING on a date-clustered table, so a string BETWEEN prunes blocks."""
        bounds = cls._validated_bounds(window)
        if bounds is None:
            return ""
        lo, hi = bounds
        return f"\nWHERE date BETWEEN '{lo}' AND '{hi}'"

    @classmethod
    def _l1_select(cls, pspec: dict, bronze_ref: str, window: Window = None) -> str:
        """
        Level-1 SELECT: cast all-STRING bronze columns to typed gold columns.
        Returns 24 columns: 6 dims + 18 metrics (engagement_rate intentionally absent).
        """
        lines = [
            "CAST(date AS DATE)   AS date",
            f"{pspec['name_literal']}  AS platform",
            "campaign_id",
            "campaign_name",
            f"{pspec['sub_id_col']}  AS sub_group_id",
            f"{pspec['sub_name_col']}  AS sub_group_name",
        ]
        for gold_col, bronze_col, bq_type, default in pspec['l1_metrics']:
            expr = cls._cast_expr(bronze_col, bq_type, default)
            lines.append(f"{expr}  AS {gold_col}")
        return "SELECT\n    " + ",\n    ".join(lines) + f"\nFROM `{bronze_ref}`" + cls._bronze_window(window)

    @classmethod
    def _quarantine_l1(cls, pspec: dict, bronze_ref: str, window: Window = None) -> str:
        """
        Minimal Level-1 for quarantine MERGE: only validation-relevant columns.
        Reads universal G1-G5 cols + platform-specific quarantine_extra_cols.
        NOTE: engagement_rate is NOT included for any platform.
        """
        # Look up spend and conversion_value entries from l1_metrics
        by_gold = {entry[0]: entry for entry in pspec['l1_metrics']}
        spend_entry = by_gold['spend']
        cv_entry    = by_gold['conversion_value']

        lines = [
            "CAST(date AS DATE)  AS date",
            "campaign_id",
            f"{pspec['sub_id_col']}  AS sub_group_id",
            cls._cast_expr(spend_entry[1], spend_entry[2], spend_entry[3]) + "  AS spend",
            "COALESCE(SAFE_CAST(NULLIF(impressions, '') AS INT64), 0)   AS impressions",
            "COALESCE(SAFE_CAST(NULLIF(clicks,      '') AS INT64), 0)   AS clicks",
            "COALESCE(SAFE_CAST(NULLIF(conversions, '') AS INT64), 0)   AS conversions",
            cls._cast_expr(cv_entry[1], cv_entry[2], cv_entry[3]) + "  AS conversion_value",
        ]
        for gold_col, bronze_col, bq_type in pspec.get('quarantine_extra_cols', []):
            expr = cls._cast_expr(bronze_col, bq_type, None)
            lines.append(f"{expr}  AS {gold_col}")
        return "SELECT\n    " + ",\n    ".join(lines) + f"\nFROM `{bronze_ref}`" + cls._bronze_window(window)

    @classmethod
    def _violation_array(cls, pspec: dict) -> str:
        """
        ARRAY_TO_STRING expression that evaluates G1-G5 (universal) +
        platform-specific checks.  G8 (engagement_rate) intentionally absent.
        """
        # Universal checks: G1-G5
        checks = [
            ('G1_NEGATIVE_SPEND',      'spend < 0'),
            ('G2_NEGATIVE_IMPRESSIONS','impressions < 0'),
            ('G3_INVALID_CLICKS',      'clicks < 0 OR clicks > impressions'),
            ('G4_INVALID_CONVERSIONS', 'conversions < 0 OR conversions > clicks'),
            ('G5_NEGATIVE_REVENUE',    'conversion_value < 0'),
        ]
        checks.extend(pspec['quarantine_checks'])  # platform-specific
        if_parts = [f"IF({cond}, '{rule}', NULL)" for rule, cond in checks]
        inner = ",\n                        ".join(if_parts)
        return (
            "ARRAY_TO_STRING(\n"
            "                ARRAY(\n"
            "                    SELECT rule FROM UNNEST([\n"
            f"                        {inner}\n"
            "                    ]) AS rule\n"
            "                    WHERE rule IS NOT NULL\n"
            "                ), '|'\n"
            "            )"
        )

    @classmethod
    def _gold_where(cls, pspec: dict) -> str:
        base = (
            "spend >= 0 AND impressions >= 0\n"
            "      AND clicks >= 0 AND clicks <= impressions\n"
            "      AND conversions >= 0 AND conversions <= clicks\n"
            "      AND conversion_value >= 0"
        )
        extra = pspec.get('gold_where_extra', '')
        return base + (f"\n      AND {extra}" if extra else "")

    # ── Shared SELECT columns for Level-2 ─────────────────────────────────────
    # Pass-throughs from L1 (24 cols) then 6 computed metrics = 30 total.
    _L2_PASSTHROUGH = (
        "date, platform, campaign_id, campaign_name, sub_group_id, sub_group_name,\n"
        "        impressions, clicks, spend, conversions, conversion_value,\n"
        "        video_views, video_watch_25, video_watch_50, video_watch_75, video_watch_100,\n"
        "        likes, shares, comments, reach, frequency,\n"
        "        quality_score, search_impression_share, avg_cpc"
    )

    # ── Public SQL generators ─────────────────────────────────────────────────

    @classmethod
    def quarantine_merge(cls, platform: str, window: Window = None) -> str:
        """Idempotent quarantine MERGE for one platform (MD5 primary key)."""
        pspec  = cls._PLATFORM_CONFIG[platform]
        qref   = Config.quarantine_ref()
        bronze = Config.bronze_ref(pspec['bronze_table'])
        q_l1   = cls._quarantine_l1(pspec, bronze, window)
        v_arr  = cls._violation_array(pspec)
        name   = pspec['name_literal']
        origin = pspec['origin']
        return f"""MERGE `{qref}` AS target
USING (
    SELECT
        TO_HEX(MD5(CONCAT(
            CAST(date AS STRING), '|', {name}, '|',
            campaign_id, '|', sub_group_id, '|', violated_rule_identifier
        )))               AS quarantine_id,
        CURRENT_TIMESTAMP() AS execution_timestamp,
        '{origin}'        AS origin_platform,
        TO_JSON_STRING(STRUCT(
            date, campaign_id, sub_group_id,
            spend, impressions, clicks, conversions, conversion_value
        ))                AS raw_record_json,
        violated_rule_identifier,
        'PENDING'         AS remediation_status
    FROM (
        SELECT
            date, campaign_id, sub_group_id,
            spend, impressions, clicks, conversions, conversion_value,
            {v_arr} AS violated_rule_identifier
        FROM ({q_l1})
    )
    WHERE LENGTH(violated_rule_identifier) > 0
) AS source
ON target.quarantine_id = source.quarantine_id
WHEN NOT MATCHED THEN INSERT ROW""".strip()

    @classmethod
    def gold_merge(cls, platform: str, window: Window = None) -> str:
        """
        Incremental MERGE for one platform.
        Level-1: casts all-STRING bronze → typed (24 cols, no engagement_rate).
        Level-2 (USING): computes engagement_rate + 5 derived metrics; applies
                         G-filter WHERE clause.
        UPDATE covers all 26 non-key gold columns.

        With `window`, the bronze source is filtered to those dates (string
        BETWEEN prunes the clustered blocks) and the ON clause adds a DATE
        BETWEEN predicate on `target` so BigQuery prunes to the gold table's
        day partitions instead of scanning all of history.
        """
        pspec  = cls._PLATFORM_CONFIG[platform]
        gold   = Config.gold_ref()
        bronze = Config.bronze_ref(pspec['bronze_table'])
        l1     = cls._l1_select(pspec, bronze, window)
        roas   = pspec['roas_expr']
        where  = cls._gold_where(pspec)

        target_window = ""
        bounds = cls._validated_bounds(window)
        if bounds is not None:
            lo, hi = bounds
            target_window = f"\nAND target.date BETWEEN DATE '{lo}' AND DATE '{hi}'"

        update_cols = [
            'campaign_name', 'sub_group_name',
            'impressions', 'clicks', 'spend', 'conversions', 'conversion_value',
            'video_views', 'video_watch_25', 'video_watch_50',
            'video_watch_75', 'video_watch_100',
            'likes', 'shares', 'comments', 'reach', 'frequency',
            'quality_score', 'search_impression_share', 'avg_cpc',
            'engagement_rate', 'cpa', 'ctr', 'cpc', 'cpm', 'roas',
        ]
        update_set = ",\n    ".join(f"target.{c} = source.{c}" for c in update_cols)

        return f"""MERGE `{gold}` AS target
USING (
    SELECT
        {cls._L2_PASSTHROUGH},
        SAFE_DIVIDE(
            CAST(likes    AS FLOAT64) +
            CAST(shares   AS FLOAT64) +
            CAST(comments AS FLOAT64),
            CAST(impressions AS FLOAT64)
        )                                                     AS engagement_rate,
        SAFE_DIVIDE(spend, CAST(conversions AS FLOAT64))      AS cpa,
        SAFE_DIVIDE(CAST(clicks AS FLOAT64), CAST(impressions AS FLOAT64)) AS ctr,
        SAFE_DIVIDE(spend, CAST(clicks AS FLOAT64))           AS cpc,
        SAFE_DIVIDE(spend * 1000.0, CAST(impressions AS FLOAT64)) AS cpm,
        {roas}                                                AS roas
    FROM ({l1})
    WHERE {where}
) AS source
ON  target.date         = source.date
AND target.platform     = source.platform
AND target.campaign_id  = source.campaign_id
AND target.sub_group_id = source.sub_group_id{target_window}
WHEN MATCHED THEN UPDATE SET
    {update_set}
WHEN NOT MATCHED THEN INSERT ROW""".strip()

    # ── Gold table schema specification ───────────────────────────────────────
    # Single source of truth for column names, BigQuery types, NOT NULL flags,
    # and column descriptions.  Used by:
    #   • create_gold_schema()  — DDL for first-run table creation
    #   • EXPECTED_GOLD_COLS check in Verifier (len = 30)
    #   • gold_unified_performance_mart.sql regeneration
    #
    # NOT NULL logic:
    #   All 6 dimension columns   → NOT NULL (validated in Script 01, R0+R6)
    #   All 18 metric columns     → NOT NULL (COALESCE(SAFE_CAST(...),0) or CAST(0,TYPE))
    #                               This includes platform-specific columns:
    #                               video_* / likes / shares / comments → 0 for Facebook/Google
    #                               reach / frequency                   → 0 for Google/TikTok
    #                               quality_score / search_impression_share / avg_cpc
    #                                                                   → 0 for Facebook/TikTok
    #   6 SAFE_DIVIDE derived cols → NULLABLE (denominator can be 0 → NULL by design)
    #
    # Format: (column_name, bq_type, not_null, description)
    _GOLD_COLUMN_SPEC: list[tuple[str, str, bool, str]] = [
        # ── Dimensions ─────────────────────────────────────────────────────
        ("date",                    "DATE",    True,  "Partition date (from bronze ingestion)."),
        ("platform",                "STRING",  True,  "Source channel: Facebook, Google, or TikTok."),
        ("campaign_id",             "STRING",  True,  "Platform campaign identifier."),
        ("campaign_name",           "STRING",  True,  "Human-readable campaign name."),
        ("sub_group_id",            "STRING",  True,  "Ad set / ad group / adgroup identifier."),
        ("sub_group_name",          "STRING",  True,  "Ad set / ad group / adgroup name."),
        # ── Core volume metrics ─────────────────────────────────────────────
        ("impressions",             "INT64",   True,  "Total ad impressions served."),
        ("clicks",                  "INT64",   True,  "Total measurable ad clicks."),
        ("spend",                   "FLOAT64", True,  "Gross ad cost (USD)."),
        ("conversions",             "INT64",   True,  "Total conversions attributed."),
        ("conversion_value",        "FLOAT64", True,  "Revenue from conversions (Google only; 0 elsewhere)."),
        # ── Video telemetry (TikTok native; 0 for Facebook/Google) ─────────
        ("video_views",             "INT64",   True,  "Total video view initiations (TikTok; 0 elsewhere)."),
        ("video_watch_25",          "INT64",   True,  "Views reaching 25%% completion (TikTok; 0 elsewhere)."),
        ("video_watch_50",          "INT64",   True,  "Views reaching 50%% completion (TikTok; 0 elsewhere)."),
        ("video_watch_75",          "INT64",   True,  "Views reaching 75%% completion (TikTok; 0 elsewhere)."),
        ("video_watch_100",         "INT64",   True,  "Views reaching 100%% completion (TikTok; 0 elsewhere)."),
        # ── Social engagement (TikTok native; 0 for Facebook/Google) ───────
        ("likes",                   "INT64",   True,  "Total user likes (TikTok; 0 elsewhere)."),
        ("shares",                  "INT64",   True,  "Total user shares (TikTok; 0 elsewhere)."),
        ("comments",                "INT64",   True,  "Total user comments (TikTok; 0 elsewhere)."),
        # ── Platform-specific reach/frequency (Facebook native; 0 elsewhere)
        ("reach",                   "INT64",   True,  "Unique audience reached (Facebook; 0 elsewhere)."),
        ("frequency",               "FLOAT64", True,  "Avg impressions per unique user (Facebook; 0 elsewhere)."),
        # ── Platform-specific quality/search (Google native; 0 elsewhere) ──
        ("quality_score",           "INT64",   True,  "Ad relevance score 1-10 (Google; 0 elsewhere)."),
        ("search_impression_share", "FLOAT64", True,  "Share of eligible search impressions (Google; 0 elsewhere)."),
        ("avg_cpc",                 "FLOAT64", True,  "Platform-reported avg cost per click (Google; 0 elsewhere)."),
        # ── Derived metrics — SAFE_DIVIDE → nullable when denominator = 0 ──
        ("engagement_rate",         "FLOAT64", False, "Derived: (likes+shares+comments)/impressions. NULL if impressions=0."),
        ("cpa",                     "FLOAT64", False, "Derived: spend/conversions. NULL if conversions=0."),
        ("ctr",                     "FLOAT64", False, "Derived: clicks/impressions. NULL if impressions=0."),
        ("cpc",                     "FLOAT64", False, "Derived: spend/clicks. NULL if clicks=0."),
        ("cpm",                     "FLOAT64", False, "Derived: spend*1000/impressions. NULL if impressions=0."),
        ("roas",                    "FLOAT64", False, "Derived: conversion_value/spend. NULL if spend=0 (0 for FB/TT)."),
    ]

    @classmethod
    def create_gold_schema(cls) -> str:
        """
        CREATE TABLE IF NOT EXISTS with explicit NOT NULL constraints and
        column descriptions.

        Design rationale (replaces CREATE OR REPLACE TABLE ... AS SELECT):
          • CREATE OR REPLACE infers schema from the SELECT — BigQuery drops
            every NOT NULL constraint and OPTIONS(description) in the process.
          • CREATE TABLE IF NOT EXISTS with explicit column definitions preserves
            the schema contract on every run.
          • The table is populated separately via incremental_transaction() —
            the same MERGE that runs on every incremental update.  First-run
            and incremental are now identical in execution logic.
          • NOT NULL on all 24 base columns is safe because every metric column
            uses COALESCE(SAFE_CAST(...), 0) or CAST(0 AS TYPE) in the L1
            select — zero is always produced, never NULL.
          • The 6 SAFE_DIVIDE derived metrics stay NULLABLE because a zero
            denominator legitimately produces NULL (e.g. campaign with no
            conversions → cpa IS NULL, which is correct — NOT zero).
        """
        gold = Config.gold_ref()
        col_lines = []
        for name, bq_type, not_null, desc in cls._GOLD_COLUMN_SPEC:
            null_clause = " NOT NULL" if not_null else "        "
            col_lines.append(
                f"  {name:<26} {bq_type:<8}{null_clause}"
                f"  OPTIONS(description=\"{desc}\")"
            )
        col_block = ",\n".join(col_lines)
        return (
            f"CREATE TABLE IF NOT EXISTS `{gold}`\n"
            f"(\n{col_block}\n)\n"
            f"PARTITION BY date\n"
            f"CLUSTER BY platform, campaign_id"
        )

    @classmethod
    def incremental_transaction(cls, window: Window = None) -> str:
        """
        Wrap all 3 gold MERGEs in a BigQuery transaction.
        Atomicity: if TikTok MERGE fails after Facebook+Google commit,
        the whole transaction rolls back — no partial-platform state.
        DDL is not allowed inside BigQuery transactions; only DML (MERGE) here.
        """
        stmts = "\n".join(cls.gold_merge(p, window) + ";" for p in cls._PLATFORM_CONFIG)
        return f"BEGIN TRANSACTION;\n{stmts}\nCOMMIT TRANSACTION;"

    @classmethod
    def bronze_total_rows_query(cls) -> str:
        """Total row count across all three bronze tables for the audit log."""
        parts = " +\n    ".join(
            f"(SELECT COUNT(*) FROM `{Config.bronze_ref(pspec['bronze_table'])}`)"
            for pspec in cls._PLATFORM_CONFIG.values()
        )
        return f"SELECT\n    {parts} AS total_rows"

# =============================================================================
# Verifier
# =============================================================================

class Verifier:
    """
    Post-execution verification.  Runs after transformation completes.
    Critical failures: sys.exit(1) via caller.
    Warning failures: logged but do not abort.
    """

    def __init__(self, executor: BQExecutor, log: logging.Logger) -> None:
        self._ex  = executor
        self._log = log

    def verify_column_count(self) -> bool:
        """
        Data Contract: gold table must have exactly 30 columns.
        Uses INFORMATION_SCHEMA (no table scan — just metadata).
        """
        sql = f"""
        SELECT COUNT(*) AS col_count
        FROM   `{Config.PROJECT}.{Config.PRODUCTION_DS}.INFORMATION_SCHEMA.COLUMNS`
        WHERE  table_name = '{Config.GOLD_TABLE}'
        """
        job  = self._ex.run_query(sql, Config.VERIFY_MAX_BYTES, "verify:col_count")
        rows = list(job.result())
        col_count = rows[0].col_count if rows else 0
        passed = (col_count == Config.EXPECTED_GOLD_COLS)
        if passed:
            self._log.info("Column count OK: %d (expected %d)",
                           col_count, Config.EXPECTED_GOLD_COLS)
        else:
            self._log.error(
                "COLUMN COUNT MISMATCH: got %d, expected %d  "
                "(Data Contract violation — check transformation SQL)",
                col_count, Config.EXPECTED_GOLD_COLS,
            )
        return passed

    def verify_row_counts(self) -> dict[str, int]:
        """
        Returns per-platform row counts in gold table.
        Also returns bronze counts for comparison.  Logs warning if mismatched
        (expected when quarantine > 0; failure-worthy only if gold has MORE rows
        than bronze — would indicate a bug).
        """
        gold_sql = f"""
        SELECT platform, COUNT(*) AS cnt
        FROM   `{Config.gold_ref()}`
        GROUP  BY platform
        ORDER  BY platform
        """
        bronze_sql = f"""
        SELECT 'Facebook' AS platform,
               COUNT(*) AS cnt
        FROM   `{Config.bronze_ref('facebook_ads_landing')}`
        UNION ALL
        SELECT 'Google', COUNT(*)
        FROM   `{Config.bronze_ref('google_ads_landing')}`
        UNION ALL
        SELECT 'TikTok', COUNT(*)
        FROM   `{Config.bronze_ref('tiktok_ads_landing')}`
        """
        gold_job   = self._ex.run_query(gold_sql,   Config.VERIFY_MAX_BYTES, "verify:gold_rows")
        bronze_job = self._ex.run_query(bronze_sql, Config.VERIFY_MAX_BYTES, "verify:bronze_rows")

        gold_counts   = {r.platform: r.cnt for r in gold_job.result()}
        bronze_counts = {r.platform: r.cnt for r in bronze_job.result()}

        total_gold   = sum(gold_counts.values())
        total_bronze = sum(bronze_counts.values())

        for platform in sorted(bronze_counts):
            g = gold_counts.get(platform, 0)
            b = bronze_counts[platform]
            quarantined = b - g
            if quarantined < 0:
                self._log.error(
                    "Row count BUG: gold has MORE rows than bronze for %s "
                    "(gold=%d, bronze=%d) — investigate MERGE key collision",
                    platform, g, b,
                )
            elif quarantined > 0:
                self._log.warning(
                    "Row count: %s  gold=%d  bronze=%d  quarantined=%d (G1-G12 violations)",
                    platform, g, b, quarantined,
                )
            else:
                self._log.info("Row count OK: %s  gold=%d == bronze=%d",
                               platform, g, b)

        self._log.info(
            "Total rows — gold: %d  bronze: %d  quarantined: %d",
            total_gold, total_bronze, total_bronze - total_gold,
        )
        return gold_counts

    def verify_financial_reconciliation(self) -> bool:
        """
        Per-platform: |bronze_spend - gold_spend| <= SPEND_TOLERANCE ($0.01).
        With clean data (0 quarantined rows) this should be exact.
        Mismatch > tolerance on a non-quarantine run indicates a bug.
        """
        bronze_sql = f"""
        SELECT 'Facebook' AS platform,
               SUM(COALESCE(SAFE_CAST(NULLIF(spend, '') AS FLOAT64), 0)) AS spend
        FROM   `{Config.bronze_ref('facebook_ads_landing')}`
        UNION ALL
        SELECT 'Google',
               SUM(COALESCE(SAFE_CAST(NULLIF(cost, '') AS FLOAT64), 0))
        FROM   `{Config.bronze_ref('google_ads_landing')}`
        UNION ALL
        SELECT 'TikTok',
               SUM(COALESCE(SAFE_CAST(NULLIF(cost, '') AS FLOAT64), 0))
        FROM   `{Config.bronze_ref('tiktok_ads_landing')}`
        """
        gold_sql = f"""
        SELECT platform, SUM(spend) AS spend
        FROM   `{Config.gold_ref()}`
        GROUP  BY platform
        ORDER  BY platform
        """
        b_job = self._ex.run_query(bronze_sql, Config.VERIFY_MAX_BYTES, "verify:bronze_spend")
        g_job = self._ex.run_query(gold_sql,   Config.VERIFY_MAX_BYTES, "verify:gold_spend")

        bronze_spend = {r.platform: r.spend for r in b_job.result()}
        gold_spend   = {r.platform: r.spend for r in g_job.result()}

        all_passed = True
        for platform in sorted(bronze_spend):
            b = bronze_spend[platform]
            g = gold_spend.get(platform, 0.0) or 0.0
            diff = abs(b - g)
            if diff <= Config.SPEND_TOLERANCE:
                self._log.info(
                    "Spend reconciliation OK: %s  bronze=$%.2f  gold=$%.2f  diff=$%.4f",
                    platform, b, g, diff,
                )
            else:
                self._log.error(
                    "SPEND MISMATCH: %s  bronze=$%.2f  gold=$%.2f  diff=$%.4f  "
                    "(tolerance=$%.2f) — quarantine or CAST error?",
                    platform, b, g, diff, Config.SPEND_TOLERANCE,
                )
                all_passed = False

        total_gold = sum(gold_spend.values())
        self._log.info("Total gold spend: $%.2f  (LLD ground truth: $%.2f)",
                       total_gold, 130_244.90)
        return all_passed



# =============================================================================
# GoldTransformer
# =============================================================================

class GoldTransformer:
    """
    Orchestrates the gold transformation.  Detects first-run vs. incremental,
    runs the appropriate path, verifies, and keeps the audit in sync.
    """

    def __init__(self, client: bigquery.Client, log: logging.Logger, window: Window = None) -> None:
        self._client   = client
        self._log      = log
        self._window   = window
        self._ex       = BQExecutor(client, log)
        self._audit    = AuditLogger(self._ex, log)
        self._sql      = SqlBuilder
        self._verifier = Verifier(self._ex, log)

    def run(self) -> None:
        # ── Phase 0: Infrastructure bootstrap ─────────────────────────────────
        # Must run BEFORE any audit logging because the audit table itself
        # might not exist yet.  If this fails, we raise immediately — no
        # attempt to write to the audit table (it may not be there).
        try:
            self._ensure_infrastructure()
        except Exception as exc:
            self._log.critical(
                "Infrastructure bootstrap FAILED — cannot proceed. "
                "Audit logging unavailable at this point. Error: %s", exc,
            )
            raise

        # ── Phase 1–N: Normal pipeline flow ───────────────────────────────────
        error_stage = "INIT"
        try:
            error_stage = "COUNT_BRONZE"
            bronze_rows = self._count_bronze_rows()

            self._audit.started(bronze_rows)

            error_stage = "DETECT_MODE"
            gold_exists = self._ex.table_exists(Config.gold_ref())
            mode = "INCREMENTAL" if gold_exists else "FIRST_RUN"
            self._log.info("Execution mode: %s  (gold table %s)",
                           mode, "EXISTS" if gold_exists else "ABSENT")
            self._audit.transforming(mode)

            error_stage = f"TRANSFORM_{mode}"
            if gold_exists:
                self._run_incremental()
            else:
                self._run_first_run()

            error_stage = "VERIFY"
            self._audit.verifying()
            # ponytail: verification reconciles all of bronze vs gold, O(history) bytes but
            # under BigQuery's 10 MB per-query minimum for ~a decade; bound it to self._window
            # once a query bills above the minimum
            gold_counts, rows_quarantined = self._run_verification(bronze_rows)
            rows_accepted = sum(gold_counts.values())

            self._audit.success(rows_accepted, rows_quarantined)
            self._log.info(
                "Script 02 COMPLETE  mode=%s  gold_rows=%d  quarantined=%d",
                mode, rows_accepted, rows_quarantined,
            )

        except Exception as exc:
            msg = str(exc)
            self._log.error("FAILED at stage=%s: %s", error_stage, msg)
            try:
                # Append-only audit: no string escaping risk, no cost guardrail hit
                self._audit.failed(msg, error_stage)
            except Exception as audit_exc:
                self._log.error("Also failed to write FAILED audit event: %s", audit_exc)
            raise

    # ── Infrastructure bootstrap ──────────────────────────────────────────────

    def _ensure_infrastructure(self) -> None:
        """
        Idempotent infrastructure bootstrap.  Creates the three BigQuery
        datasets and the two metadata tables (audit + quarantine) with
        explicit schemas and DAY partitioning if they do not already exist.

        Design decisions:
          • Uses client.create_dataset(exists_ok=True) — single API call;
            no pre-flight get_dataset needed.
          • Datasets are created in Config.BQ_LOCATION ("US") to match the
            existing bronze tables (confirmed by the 404 error location hint).
          • Audit and quarantine tables are created with explicit SchemaField
            lists rather than relying on JSON auto-detection — ensures correct
            types (e.g., TIMESTAMP vs STRING) and DAY partitioning with
            90-day expiry that auto-detect cannot set.
          • Gold mart table is NOT created here — SqlBuilder.create_gold_schema()
            handles it with the correct PARTITION + CLUSTER DDL.
        """
        self._log.info("Infrastructure: verifying / creating BQ resources ...")

        # ── 1. Datasets ────────────────────────────────────────────────────
        for ds_id in [Config.BRONZE_DS, Config.STAGING_DS, Config.PRODUCTION_DS]:
            ds_obj = bigquery.Dataset(f"{Config.PROJECT}.{ds_id}")
            ds_obj.location = Config.BQ_LOCATION
            self._client.create_dataset(ds_obj, exists_ok=True)
            self._log.info("  dataset OK: %s", ds_id)

        # ── 2. Audit table ─────────────────────────────────────────────────
        # Append-only ledger; QUALIFY ROW_NUMBER() view gives latest status.
        # Partitioned on started_at so UPDATE-style queries (if ever added)
        # scan only one day's partition.
        _AUDIT_SCHEMA = [
            bigquery.SchemaField("audit_id",         "STRING",    mode="REQUIRED"),
            bigquery.SchemaField("file_name",         "STRING"),
            bigquery.SchemaField("file_size_bytes",   "INT64"),
            bigquery.SchemaField("platform",          "STRING"),
            bigquery.SchemaField("started_at",        "TIMESTAMP", mode="REQUIRED"),
            bigquery.SchemaField("last_updated_at",   "TIMESTAMP", mode="REQUIRED"),
            bigquery.SchemaField("completed_at",      "TIMESTAMP"),
            bigquery.SchemaField("rows_in_file",      "INT64"),
            bigquery.SchemaField("rows_accepted",     "INT64"),
            bigquery.SchemaField("rows_quarantined",  "INT64"),
            bigquery.SchemaField("rows_merged",       "INT64"),
            bigquery.SchemaField("status",            "STRING",    mode="REQUIRED"),
            bigquery.SchemaField("error_message",     "STRING"),
            bigquery.SchemaField("error_stage",       "STRING"),
        ]
        audit_tbl = bigquery.Table(Config.audit_ref(), schema=_AUDIT_SCHEMA)
        audit_tbl.time_partitioning = bigquery.TimePartitioning(
            field="started_at",
            expiration_ms=90 * 24 * 3_600 * 1_000,   # 90-day auto-expiry (LLD §10.4)
        )
        self._client.create_table(audit_tbl, exists_ok=True)
        self._log.info("  table OK: %s", Config.AUDIT_TABLE)

        # ── 3. Quarantine table ────────────────────────────────────────────
        # WRITE_APPEND via quarantine MERGE; MD5 quarantine_id prevents dups.
        _QUARANTINE_SCHEMA = [
            bigquery.SchemaField("quarantine_id",            "STRING",    mode="REQUIRED"),
            bigquery.SchemaField("execution_timestamp",      "TIMESTAMP", mode="REQUIRED"),
            bigquery.SchemaField("origin_platform",          "STRING"),
            bigquery.SchemaField("raw_record_json",          "STRING"),
            bigquery.SchemaField("violated_rule_identifier", "STRING"),
            bigquery.SchemaField("remediation_status",       "STRING"),
        ]
        q_tbl = bigquery.Table(Config.quarantine_ref(), schema=_QUARANTINE_SCHEMA)
        q_tbl.time_partitioning = bigquery.TimePartitioning(
            field="execution_timestamp",
            expiration_ms=90 * 24 * 3_600 * 1_000,
        )
        self._client.create_table(q_tbl, exists_ok=True)
        self._log.info("  table OK: %s", Config.QUARANTINE_TABLE)

        self._log.info("Infrastructure: all resources verified ✓")

    # ── First-run path ────────────────────────────────────────────────────────

    def _run_first_run(self) -> None:
        """
        First-run: 5 BigQuery jobs.

        1-3: Quarantine MERGEs per platform (idempotent, route bad rows out).
        4:   CREATE TABLE IF NOT EXISTS — creates the empty gold table with
             the full NOT NULL schema contract.  DDL only; no data scanned.
        5:   incremental_transaction() — the same BEGIN/COMMIT MERGE transaction
             used on every incremental run.  On an empty table every row is
             WHEN NOT MATCHED → INSERT.  Subsequent runs UPDATE or INSERT.

        Why this is better than the old CREATE OR REPLACE TABLE ... AS SELECT:
          • CREATE OR REPLACE destroys NOT NULL constraints and column
            descriptions every time it runs (BigQuery infers schema from SELECT
            and cannot preserve metadata defined in a prior DDL).
          • CREATE TABLE IF NOT EXISTS preserves the schema contract forever.
          • First-run and incremental now share the same MERGE logic — no two
            separate code paths that can drift out of sync.
        """
        platforms = list(self._sql._PLATFORM_CONFIG.keys())

        if self._window is not None:
            self._log.info("First run: window ignored, building all of history")

        for platform in platforms:
            self._log.info("First-run: quarantine MERGE — %s", platform)
            self._ex.run_query(
                self._sql.quarantine_merge(platform),
                max_bytes=Config.QUARANTINE_MERGE_MAX_BYTES,
                description=f"first_run:quarantine:{platform}",
            )

        self._log.info(
            "First-run: CREATE TABLE IF NOT EXISTS — %d cols (%d NOT NULL, 6 nullable derived)",
            len(self._sql._GOLD_COLUMN_SPEC),
            sum(1 for *_, not_null, _ in self._sql._GOLD_COLUMN_SPEC if not_null),
        )
        # DDL — no data scanned; use VERIFY_MAX_BYTES as a safe non-zero cap
        self._ex.run_query(
            self._sql.create_gold_schema(),
            max_bytes=Config.VERIFY_MAX_BYTES,
            description="first_run:create_gold_schema",
        )

        self._log.info("First-run: populate gold via MERGE transaction")
        self._ex.run_query(
            self._sql.incremental_transaction(),
            max_bytes=Config.GOLD_TXN_MAX_BYTES,
            description="first_run:gold_merge_transaction",
        )
        self._log.info("First-run complete — gold table created with NOT NULL schema and populated")

    # ── Incremental path ──────────────────────────────────────────────────────

    def _run_incremental(self) -> None:
        """
        Incremental: 2 phases.

        Phase 1 — Quarantine MERGEs (outside transaction; idempotent):
          Each run in its own job.  MD5 primary key prevents double-quarantine.

        Phase 2 — Gold MERGEs (inside BEGIN/COMMIT transaction):
          All 3 platforms in one atomic multi-statement job.
          If TikTok's MERGE fails after Facebook+Google succeed, BigQuery
          rolls back the entire transaction — no partial-platform state.
        """
        platforms = list(self._sql._PLATFORM_CONFIG.keys())

        self._log.info("Incremental: window %s", self._window)

        # Phase 1: quarantine MERGEs
        for platform in platforms:
            self._log.info("Incremental: quarantine MERGE — %s", platform)
            q_job = self._ex.run_query(
                self._sql.quarantine_merge(platform, self._window),
                max_bytes=Config.QUARANTINE_MERGE_MAX_BYTES,
                description=f"incremental:quarantine:{platform}",
            )
            inserted = (q_job.dml_stats.inserted_row_count or 0)
            self._log.info("  quarantine inserted: %d", inserted)

        # Phase 2: gold MERGEs in a single transaction
        self._log.info("Incremental: BEGIN gold MERGEs transaction (3 platforms)")
        self._ex.run_query(
            self._sql.incremental_transaction(self._window),
            max_bytes=Config.GOLD_TXN_MAX_BYTES,
            description="incremental:gold_transaction",
        )
        self._log.info("Incremental: gold MERGEs COMMITTED")

    # ── Verification ──────────────────────────────────────────────────────────

    def _run_verification(
        self, bronze_rows: int
    ) -> tuple[dict[str, int], int]:
        """
        Returns (gold_row_counts_by_platform, total_quarantined_rows).
        Raises on column-count mismatch (Data Contract violation).
        """
        col_ok = self._verifier.verify_column_count()
        if not col_ok:
            raise RuntimeError(
                f"Data Contract violated: gold table column count != "
                f"{Config.EXPECTED_GOLD_COLS}."
            )
        gold_counts = self._verifier.verify_row_counts()
        self._verifier.verify_financial_reconciliation()
        quarantined = max(bronze_rows - sum(gold_counts.values()), 0)
        return gold_counts, quarantined

    def _count_bronze_rows(self) -> int:
        job  = self._ex.run_query(
            self._sql.bronze_total_rows_query(),
            max_bytes=Config.VERIFY_MAX_BYTES,
            description="count:bronze_total",
        )
        rows = list(job.result())
        return int(rows[0].total_rows) if rows else 0


# =============================================================================
# Entry point
# =============================================================================

def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(
        description="Bronze → gold. With --start/--end only those dates are read and merged."
    )
    ap.add_argument("--start", help="first date, YYYY-MM-DD")
    ap.add_argument("--end", help="last date, YYYY-MM-DD")
    args = ap.parse_args(argv)
    if (args.start is None) != (args.end is None):
        ap.error("--start and --end go together")
    if args.start is not None and args.end is not None and args.start > args.end:
        ap.error("--start must not be after --end")
    window: Window = (args.start, args.end) if args.start else None

    log = setup_logging(Config.LOGS_DIR / "02_run_transformations.log")
    log.info("=" * 72)
    log.info("Script 02 — Gold Transformation  started at %s",
             datetime.now(timezone.utc).isoformat())
    log.info("=" * 72)

    try:
        client = common.bq_client()
        log.info("BigQuery client initialised  project=%s", client.project)
    except Exception as exc:
        log.error("Failed to initialise BigQuery client: %s", exc)
        log.error("Run: gcloud auth application-default login")
        sys.exit(1)

    transformer = GoldTransformer(client, log, window)
    try:
        transformer.run()
    except Exception as exc:
        log.error("Unrecoverable failure: %s", exc)
        sys.exit(1)


if __name__ == "__main__":
    main()